x-common-environment: &common-environment
  TZ: Asia/Shanghai
  DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/fast_voice
  DATABASE_URL_SYNC: postgresql+psycopg://postgres:postgres@db:5432/fast_voice
  DB_POOL_SIZE: "10"
  DB_MAX_OVERFLOW: "20"
  DB_POOL_TIMEOUT_SECONDS: "30"
  DB_POOL_RECYCLE_SECONDS: "1800"
  REDIS_URL: redis://redis:6379/0
  CELERY_BROKER_URL: redis://redis:6379/1
  CELERY_RESULT_BACKEND: redis://redis:6379/2
  JWT_SECRET: f77a006515c2020c609f248b31c56a09
  DATA_DIR: /data
  VOICE_SVC_BASE_URL: "http://192.168.1.5:4000"
  VOICE_TTS_BASE_URL: "http://192.168.1.5:7000"
  REGISTER_FREE_POINT: "10000000"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      <<: *common-environment
      AUTO_CREATE_DB: true
      ADMIN_BOOTSTRAP: true
      ADMIN_EMAIL: admin@autogame.ai
      ADMIN_PASSWORD: 123456
    volumes:
      - fast_voice_data:/data
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["uv", "run", "celery", "-A", "app.tasks.celery_app:celery_app", "worker", "-l", "DEBUG", "-Q", "tts,clone"]
    environment:
      <<: *common-environment
      AUTO_CREATE_DB: false
      ADMIN_BOOTSTRAP: false
    volumes:
      - fast_voice_data:/data
    depends_on:
      - db
      - redis
  db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: fast_voice
      TZ: Asia/Shanghai
    volumes:
      - fast_voice_db:/var/lib/postgresql/data
  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  fast_voice_db:
  fast_voice_data:


